<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0-windows</TargetFramework>
	  <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FirebirdSql.Data.FirebirdClient" Version="10.3.4" />
    <PackageReference Include="log4net" Version="3.3.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.11" />
    <PackageReference Include="Svg" Version="3.4.8" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RnsLibrary">
      <HintPath>..\Dll\RnsLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Res.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Res.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Res.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Res.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

	<PropertyGroup>
		<NoWarn>$(NoWarn);CS8765;CS8767</NoWarn>
	</PropertyGroup>

	
</Project>
