//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     파일 내용을 변경하면 코드를 다시 생성할 때 손실될 수 있습니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFMSSediDll {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Res() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AFMSSediDll.Source.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string icon_arrow_down {
            get {
                return ResourceManager.GetString("icon_arrow_down", resourceCulture);
            }
        }

        internal static string icon_arrow_left {
            get {
                return ResourceManager.GetString("icon_arrow_left", resourceCulture);
            }
        }

        internal static string icon_arrow_right {
            get {
                return ResourceManager.GetString("icon_arrow_right", resourceCulture);
            }
        }

        internal static string icon_calender {
            get {
                return ResourceManager.GetString("icon_calender", resourceCulture);
            }
        }

        internal static string icon_export {
            get {
                return ResourceManager.GetString("icon_export", resourceCulture);
            }
        }

        internal static string icon_flowRate {
            get {
                return ResourceManager.GetString("icon_flowRate", resourceCulture);
            }
        }

        internal static string icon_flowRate_select {
            get {
                return ResourceManager.GetString("icon_flowRate_select", resourceCulture);
            }
        }

        internal static string icon_flowVelocity {
            get {
                return ResourceManager.GetString("icon_flowVelocity", resourceCulture);
            }
        }

        internal static string icon_flowVelocity_select {
            get {
                return ResourceManager.GetString("icon_flowVelocity_select", resourceCulture);
            }
        }

        internal static string icon_layout11_off {
            get {
                return ResourceManager.GetString("icon_layout11_off", resourceCulture);
            }
        }

        internal static string icon_layout11_on {
            get {
                return ResourceManager.GetString("icon_layout11_on", resourceCulture);
            }
        }

        internal static string icon_layout12_off {
            get {
                return ResourceManager.GetString("icon_layout12_off", resourceCulture);
            }
        }

        internal static string icon_layout12_on {
            get {
                return ResourceManager.GetString("icon_layout12_on", resourceCulture);
            }
        }

        internal static string icon_layout21_off {
            get {
                return ResourceManager.GetString("icon_layout21_off", resourceCulture);
            }
        }

        internal static string icon_layout21_on {
            get {
                return ResourceManager.GetString("icon_layout21_on", resourceCulture);
            }
        }

        internal static string icon_layout22_off {
            get {
                return ResourceManager.GetString("icon_layout22_off", resourceCulture);
            }
        }

        internal static string icon_layout22_on {
            get {
                return ResourceManager.GetString("icon_layout22_on", resourceCulture);
            }
        }

        internal static string icon_measure_off {
            get {
                return ResourceManager.GetString("icon_measure_off", resourceCulture);
            }
        }

        internal static string icon_measure_on {
            get {
                return ResourceManager.GetString("icon_measure_on", resourceCulture);
            }
        }

        internal static string icon_search_off {
            get {
                return ResourceManager.GetString("icon_search_off", resourceCulture);
            }
        }

        internal static string icon_search_on {
            get {
                return ResourceManager.GetString("icon_search_on", resourceCulture);
            }
        }

        internal static string icon_setting {
            get {
                return ResourceManager.GetString("icon_setting", resourceCulture);
            }
        }

        internal static string icon_titlebar_close {
            get {
                return ResourceManager.GetString("icon_titlebar_close", resourceCulture);
            }
        }

        internal static string icon_titlebar_close_w {
            get {
                return ResourceManager.GetString("icon_titlebar_close_w", resourceCulture);
            }
        }

        internal static string icon_titlebar_max {
            get {
                return ResourceManager.GetString("icon_titlebar_max", resourceCulture);
            }
        }

        internal static string icon_titlebar_max_w {
            get {
                return ResourceManager.GetString("icon_titlebar_max_w", resourceCulture);
            }
        }

        internal static string icon_titlebar_min_w {
            get {
                return ResourceManager.GetString("icon_titlebar_min_w", resourceCulture);
            }
        }

        internal static string icon_vth {
            get {
                return ResourceManager.GetString("icon_vth", resourceCulture);
            }
        }

        internal static string icon_vth_select {
            get {
                return ResourceManager.GetString("icon_vth_select", resourceCulture);
            }
        }

        internal static string icon_waterLevel {
            get {
                return ResourceManager.GetString("icon_waterLevel", resourceCulture);
            }
        }

        internal static string icon_waterLevel_select {
            get {
                return ResourceManager.GetString("icon_waterLevel_select", resourceCulture);
            }
        }

        internal static string toggle_off {
            get {
                return ResourceManager.GetString("toggle_off", resourceCulture);
            }
        }

        internal static string toggle_off_w {
            get {
                return ResourceManager.GetString("toggle_off_w", resourceCulture);
            }
        }

        internal static string toggle_on {
            get {
                return ResourceManager.GetString("toggle_on", resourceCulture);
            }
        }

        internal static string toggle_on_w {
            get {
                return ResourceManager.GetString("toggle_on_w", resourceCulture);
            }
        }
    }
}
